services:
  - type: web
    name: reimbursement-api
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    branch: main
